zookeeper:
  zookeeper_hosts: "10.213.37.47:2181"
  keywords_table: "/performance-forecasting/ctr-score-generator/keywords-table"
  # din_ad_keywords_09172020
  gucdocs_loaded_table: "/performance-forecasting/ctr-score-generator/din-ucdoc-loaded-table"
  # din_gucdocs_loaded_09172020
  es_host: "/performance-forecasting/inventory-updater/es-host"
  # 10.213.37.41
  es_port: "/performance-forecasting/inventory-updater/es-port"
  # 9200
  ims_inventory_serving_url: "/performance-forecasting/inventory-updater/ims-inventory-serving-url"
  # http://10.213.37.40:8090/imsservice/api/inventory/count
  ims_inventory_serving_url_daily: "/performance-forecasting/inventory-updater/ims-inventory-serving-url-daily"
  # http://10.213.37.40:8090/imsservice/api/inventory/daily/count
  es_index_prefix: "/performance-forecasting/inventory-updater/es-index-prefix"
  # din_es_gucdocs
  es_type: "/performance-forecasting/inventory-updater/es-type"
  # _doc
  es_starting_day: "/performance-forecasting/inventory-updater/es-starting-day"
  # 2020-07-01
  es_ending_day: "/performance-forecasting/inventory-updater/es-ending-day"
  # 2020-07-10
  es_starting_hour: "/performance-forecasting/inventory-updater/es-starting-hour"
  # 0
  es_ending_hour: "/performance-forecasting/inventory-updater/es-ending-hour"
  # 23
  es_index: "/performance-forecasting/inventory-updater/es-index"
  # din_es_gucdocs_2020-11-12_20:35:46