es_host: '10.193.217.111'
es_port: '9200'
es_predictions_index: 'predictions_01202020'
es_predictions_type: 'doc'
es_tbr_index: 'tbr_test_10012019'
es_tbr_type: 'doc'
es_booking_index: 'bookings_03242020'
es_booking_type: 'doc'
es_bb_index: 'booking_buckets'
es_bb_type: 'doc'
