log:
  level: 'WARN' # log level for spark and app
pipeline:
  main_clean:
    data_input:
      persona_table_name: "ads_persona_0520"
      clicklog_table_name: "ads_clicklog_0520"
      showlog_table_name: "ads_showlog_0520"
      load_logs_in_minutes: 144000 #1440/day
      keywords_table: "din_ad_keywords_08212020" #if this keywords table name is changed, set the below to True.
      create_keywords: False # set True for first run, then keep False to use the created table.
    data_output:
      persona_output_table: 'din_persona_09172020'
      clicklog_output_table: 'din_clicklog_09172020'
      showlog_output_table: 'din_showlog_09172020'
    conditions: {
      'new_slot_id_list': [  
        '06',
        '11',
        '05',
        '04',
        '03',
        '02',
        '01',
        'l03493p0r3',
        'x0ej5xhk60kjwq',
        'g7m2zuits8',
        'w3wx3nv9ow5i97',
        'a1nvkhk62q',
        'g9iv6p4sjy',
        'c4n08ku47t',
        'b6le0s4qo8',
        'd9jucwkpr3',
        'p7gsrebd4m',
        'a8syykhszz',
        'l2d4ec6csv',
        'j1430itab9wj3b',
        's4z85pd1h8',
        'z041bf6g4s',
        '71bcd2720e5011e79bc8fa163e05184e',
        'a47eavw7ex',
        '68bcd2720e5011e79bc8fa163e05184e',
        '66bcd2720e5011e79bc8fa163e05184e',
        '72bcd2720e5011e79bc8fa163e05184e',
        'f1iprgyl13',
        'q4jtehrqn2',
        'm1040xexan',
        'd971z9825e',
        'a290af82884e11e5bdec00163e291137',
        'w9fmyd5r0i',
        'x2fpfbm8rt',
        'e351de37263311e6af7500163e291137',
        'k4werqx13k',
        '5cd1c663263511e6af7500163e291137',
        '17dd6d8098bf11e5bdec00163e291137',
        'd4d7362e879511e5bdec00163e291137',
        '15e9ddce941b11e5bdec00163e291137'
      ],
      'new_slot_id_app_name_list': [
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Magazine',
        'Huawei Browser',
        'Huawei Video',
        'Huawei Video',
        'Huawei Video',
        'Huawei Music',
        'Huawei Music',
        'Huawei Music',
        'Huawei Music',
        'Huawei Reading',
        'Huawei Reading',
        'Huawei Reading',
        'Huawei Reading',
        'Video 1.0',
        'Video 2.0',
        'Tencent Video',
        'AI assistant',
        'AI assistant',
        'AI assistant',
        'AI assistant',
        'Huawei Video',
        'Huawei Video',
        'Huawei Video',
        'Video 1.0',
        'Themes',
        'Huawei Music',
        'Huawei Reading',
        'Huawei Reading',
        'Huawei Reading',
        'Huawei Reading',
        'Honor Reading',
        'Video 1.0',
        'Video 2.0',
        'HiSkytone'
      ],
      'starting_date': '2019-12-19',
      'ending_date': '2020-04-15'
    }
  main_logs:
    interval_time_in_seconds: 86400 # group logs in interval time.
    logs_output_table_name: 'din_logs_09172020'
  main_trainready:
    trainready_output_table: 'din_trainready_09172020'
  tfrecords:
    tfrecords_statistics_path: 'din.tfrecord_statistics.09172020.pkl'
    tfrecords_hdfs_path: 'din.tfrecord.09172020' # it is hdfs location for tfrecords, over-writes the existing files
  forecasting:
    generate_testing_datasets: False # set to True for the first run.
    history_ucdocs_table_name: 'din_history_ucdocs_09172020_gdin'
    testing_ucdocs_table_name: 'din_testing_ucdocs_09172020_gdin'
    length: 30
    cutting_date: '2020-03-20'
    impressions_ratio: [0.1, 0.2, 0.3] # take ratios of keywords' testing impressions as simulated queries.
    random_testing_number: 10 # the total number of random testing repeated.

predictor:
  url: 'http://10.193.217.105:8501/v1/models/gdin:predict'
  tfrecords_statistics_path: 'din.tfrecord_statistics.08282020.pkl'
  tfrecords_hdfs_path: 'din.tfrecord.08282020' # it is hdfs location for tfrecords, over-writes the existing files
  length: 6
  cutting_date: 1584748800
  tfrecord_location: '/home/faezeh/din.tfrecord.08042020'
  stats: '/home/faezeh/din.tf_statistics.08042020.pkl'






